teams:
  - name: briolette-maintainers
    maintainers:
      - ryjones
    members:
      - redpig
  - name: lf-staff
    maintainers:
      - ryjones
      - jwagantall
    members:
      - thelinuxfoundation
repositories:
  - name: governance
    teams:
      lf-staff: maintain
      briolette-maintainers: maintain
    visibility: public
